# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zjazd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_motorniczego', models.DecimalField(decimal_places=0, max_digits=10)),
                ('linia_brygada', models.CharField(max_length=20)),
                ('nr_tramwaju', models.DecimalField(decimal_places=0, max_digits=6)),
                ('opis_usterki', models.TextField()),
                ('data_godzina', models.DateTimeField()),
                ('symbol', models.CharField(max_length=5)),
                ('opis_naprawy', models.TextField()),
                ('kto_naprawil', models.CharField(max_length=200)),
            ],
        ),
    ]
