# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kzjazdow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zjazd',
            name='nr_tramwaju',
            field=models.CharField(max_length=5),
        ),
    ]
