# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kzjazdow', '0002_auto_20160728_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zjazd',
            name='linia_brygada',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='zjazd',
            name='nr_motorniczego',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='zjazd',
            name='nr_tramwaju',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='zjazd',
            name='symbol',
            field=models.CharField(max_length=8),
        ),
    ]
