# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kzjazdow', '0003_auto_20160729_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zjazd',
            name='data_godzina',
        ),
        migrations.AddField(
            model_name='zjazd',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zjazd',
            name='godzina',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
