# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kzjazdow', '0004_auto_20160730_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zjazd',
            options={'verbose_name': 'Zjazd techniczny', 'verbose_name_plural': 'Zjazdy techniczne'},
        ),
        migrations.AlterField(
            model_name='zjazd',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='zjazd',
            name='godzina',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='zjazd',
            name='kto_naprawil',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='zjazd',
            name='linia_brygada',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='zjazd',
            name='nr_motorniczego',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='zjazd',
            name='opis_naprawy',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='zjazd',
            name='symbol',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
